CREATE DATABASE IF NOT EXISTS police_fir_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE police_fir_system;

CREATE TABLE IF NOT EXISTS stations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  code VARCHAR(30) NOT NULL UNIQUE,
  city VARCHAR(80) NOT NULL,
  address VARCHAR(255) NULL,
  phone VARCHAR(30) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN', 'OFFICER') NOT NULL DEFAULT 'OFFICER',
  station_id INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (station_id) REFERENCES stations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS firs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fir_number VARCHAR(60) NOT NULL UNIQUE,
  complainant_name VARCHAR(120) NOT NULL,
  complainant_cnic VARCHAR(25) NOT NULL,
  complainant_phone VARCHAR(30) NOT NULL,
  incident_type VARCHAR(80) NOT NULL,
  incident_datetime DATETIME NOT NULL,
  location VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('Open', 'Investigating', 'Closed') NOT NULL DEFAULT 'Open',
  station_id INT NOT NULL,
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (station_id) REFERENCES stations(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
